import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.REACT_APP_SUPABASE_URL;
const supabaseAnonKey = process.env.REACT_APP_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error(
    '⚠️  Faltan variables de entorno de Supabase.\n' +
    'Copia .env.example como .env.local y llena tus credenciales.\n' +
    'Consíguelas en: https://app.supabase.com → tu proyecto → Settings → API'
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/*
═══════════════════════════════════════════════════════
  SQL PARA CREAR LA TABLA EN SUPABASE
  
  Ve a: https://app.supabase.com
  → Tu proyecto → SQL Editor → New Query
  Pega y ejecuta el siguiente SQL:
═══════════════════════════════════════════════════════

create table if not exists patterns (
  id          bigint generated by default as identity primary key,
  nombre      text        not null,
  emoji       text        not null default '🧶',
  dificultad  text        not null default 'Principiante',
  estado      text        not null default 'En progreso',
  talla       text,
  aguja       text,
  hilos       text[]      default '{}',
  materiales  text,
  notas       text,
  pasos       jsonb       default '[]',
  imagen_url  text,
  color       text        not null default '#FAD2E1',
  fecha       date        not null default now(),
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- Habilitar Row Level Security (RLS) — por ahora acceso público de lectura/escritura
-- Cuando agregues autenticación, ajusta estas políticas
alter table patterns enable row level security;

create policy "Acceso público"
  on patterns for all
  using (true)
  with check (true);

-- Índice para búsqueda por nombre
create index if not exists patterns_nombre_idx on patterns using gin(to_tsvector('spanish', nombre));

═══════════════════════════════════════════════════════
  STORAGE BUCKET PARA IMÁGENES
  
  Ve a: Supabase → Storage → New bucket
  - Nombre: pattern-images
  - Public bucket: ✅ activado
  
  Luego en SQL Editor ejecuta:
═══════════════════════════════════════════════════════

insert into storage.buckets (id, name, public)
values ('pattern-images', 'pattern-images', true)
on conflict do nothing;

create policy "Subida pública de imágenes"
  on storage.objects for insert
  with check (bucket_id = 'pattern-images');

create policy "Lectura pública de imágenes"
  on storage.objects for select
  using (bucket_id = 'pattern-images');

create policy "Borrar imágenes propias"
  on storage.objects for delete
  using (bucket_id = 'pattern-images');

*/
