import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';

/*
═══════════════════════════════════════════════════════════════
  SQL — ejecuta en Supabase → SQL Editor antes de usar

  create table if not exists inventory (
    id            bigint generated by default as identity primary key,
    user_id       uuid references auth.users not null default auth.uid(),
    tipo          text not null,           -- 'hilo' | 'material'
    nombre        text not null,
    marca         text,
    color         text,
    color_hex     text default '#C9A96E',
    subtipo       text,                    -- hilo: 'chenille','acrílico','algodón'...
                                           -- material: 'relleno','ojo_seguridad','llavero','etiqueta','tarjeta','caja','otro'
    grosor_mm     numeric,                 -- solo hilos
    tipo_gancho   text,                    -- solo hilos
    unidad        text not null default 'g', -- 'g' | 'unidad'
    stock_total   numeric not null default 0,
    stock_usado   numeric not null default 0,
    alerta_minimo numeric not null default 30,
    costo_unitario numeric not null default 0, -- costo por gramo o por unidad
    notas         text,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now()
  );

  alter table inventory enable row level security;

  create policy "Ver mi inventario"
    on inventory for select using (auth.uid() = user_id);
  create policy "Crear en mi inventario"
    on inventory for insert with check (auth.uid() = user_id);
  create policy "Editar mi inventario"
    on inventory for update using (auth.uid() = user_id);
  create policy "Borrar de mi inventario"
    on inventory for delete using (auth.uid() = user_id);
═══════════════════════════════════════════════════════════════
*/

export function useInventory(userId) {
  const [items,   setItems]   = useState([]);
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState(null);

  const load = useCallback(async () => {
    if (!userId) return;
    setLoading(true);
    setError(null);
    const { data, error: err } = await supabase
      .from('inventory')
      .select('*')
      .eq('user_id', userId)
      .order('tipo')
      .order('nombre');
    if (err) setError(err.message);
    else     setItems(data || []);
    setLoading(false);
  }, [userId]);

  useEffect(() => { load(); }, [load]);

  // ── Guardar (crear o editar) ──
  const saveItem = useCallback(async (form) => {
    const payload = {
      user_id:       userId,
      tipo:          form.tipo,
      nombre:        form.nombre,
      marca:         form.marca         || null,
      color:         form.color         || null,
      color_hex:     form.color_hex     || '#C9A96E',
      subtipo:       form.subtipo       || null,
      grosor_mm:     form.grosor_mm     || null,
      tipo_gancho:   form.tipo_gancho   || null,
      unidad:        form.unidad        || 'g',
      stock_total:   Number(form.stock_total)   || 0,
      stock_usado:   Number(form.stock_usado)   || 0,
      alerta_minimo: Number(form.alerta_minimo) || 30,
      costo_unitario:Number(form.costo_unitario)|| 0,
      notas:         form.notas         || null,
      updated_at:    new Date().toISOString(),
    };

    if (form.id) {
      const { data, error: err } = await supabase
        .from('inventory').update(payload).eq('id', form.id).select().single();
      if (err) throw new Error(err.message);
      setItems(prev => prev.map(i => i.id === form.id ? data : i));
      return data;
    } else {
      const { data, error: err } = await supabase
        .from('inventory').insert(payload).select().single();
      if (err) throw new Error(err.message);
      setItems(prev => [...prev, data]);
      return data;
    }
  }, [userId]);

  // ── Eliminar ──
  const deleteItem = useCallback(async (id) => {
    const { error: err } = await supabase.from('inventory').delete().eq('id', id);
    if (err) throw new Error(err.message);
    setItems(prev => prev.filter(i => i.id !== id));
  }, []);

  // ── Actualizar stock usado (cuando se completa un patrón) ──
  const updateUsed = useCallback(async (id, gramsUsed) => {
    const item = items.find(i => i.id === id);
    if (!item) return;
    const newUsed = Math.min(item.stock_total, item.stock_usado + gramsUsed);
    const { data, error: err } = await supabase
      .from('inventory')
      .update({ stock_usado: newUsed, updated_at: new Date().toISOString() })
      .eq('id', id).select().single();
    if (err) throw new Error(err.message);
    setItems(prev => prev.map(i => i.id === id ? data : i));
    return data;
  }, [items]);

  // ── Derived ──
  const stockBajoItems = items.filter(i =>
    (i.stock_total - i.stock_usado) <= i.alerta_minimo
  );

  return {
    items, loading, error,
    saveItem, deleteItem, updateUsed,
    stockBajoItems,
    reload: load,
  };
}
