import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';

/*
═══════════════════════════════════════════════════════════════
  MIGRACIÓN SQL — ejecuta en Supabase → SQL Editor

  1. Agrega columna entradas (si no existe):
     alter table inventory
       add column if not exists entradas numeric not null default 0;

  2. Si es tabla nueva, usa este CREATE completo:

  create table if not exists inventory (
    id             bigint generated by default as identity primary key,
    user_id        uuid references auth.users not null default auth.uid(),
    tipo           text not null,
    nombre         text not null,
    marca          text,
    color          text,
    color_hex      text default '#C9A96E',
    subtipo        text,
    grosor_mm      numeric,
    tipo_gancho    text,
    unidad         text not null default 'g',
    stock_inicial  numeric not null default 0,   -- nunca cambia tras creación
    entradas       numeric not null default 0,   -- acumula reposiciones
    stock_usado    numeric not null default 0,   -- acumula salidas / uso
    alerta_minimo  numeric not null default 30,
    costo_unitario numeric not null default 0,
    notas          text,
    created_at     timestamptz default now(),
    updated_at     timestamptz default now()
  );

  -- stock_disponible = stock_inicial + entradas - stock_usado
  -- Nunca se guarda en BD, siempre se calcula.

  alter table inventory enable row level security;
  create policy "Ver mi inventario"    on inventory for select using (auth.uid() = user_id);
  create policy "Crear en mi inventario" on inventory for insert with check (auth.uid() = user_id);
  create policy "Editar mi inventario" on inventory for update using (auth.uid() = user_id);
  create policy "Borrar de mi inventario" on inventory for delete using (auth.uid() = user_id);

  -- Si ya tenías la tabla con stock_total, renómbrala:
  -- alter table inventory rename column stock_total to stock_inicial;
═══════════════════════════════════════════════════════════════
*/

export function useInventory(userId) {
  const [items,   setItems]   = useState([]);
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState(null);

  const load = useCallback(async () => {
    if (!userId) return;
    setLoading(true);
    setError(null);
    const { data, error: err } = await supabase
      .from('inventory')
      .select('*')
      .eq('user_id', userId)
      .order('tipo')
      .order('nombre');
    if (err) setError(err.message);
    else     setItems(data || []);
    setLoading(false);
  }, [userId]);

  useEffect(() => { load(); }, [load]);

  // ── Guardar (crear o editar) ──────────────────────────────────
  // Al crear: stock_inicial queda fijo, entradas = 0, stock_usado = 0.
  // Al editar: solo se puede modificar stock_inicial si el usuario
  //            lo cambia explícitamente (ajuste de inventario físico).
  const saveItem = useCallback(async (form) => {
    const payload = {
      user_id:        userId,
      tipo:           form.tipo,
      nombre:         form.nombre,
      marca:          form.marca          || null,
      color:          form.color          || null,
      color_hex:      form.color_hex      || '#C9A96E',
      subtipo:        form.subtipo        || null,
      grosor_mm:      form.grosor_mm      || null,
      tipo_gancho:    form.tipo_gancho    || null,
      unidad:         form.unidad         || 'g',
      stock_inicial:  Number(form.stock_inicial)  || 0,
      entradas:       Number(form.entradas)        || 0,
      stock_usado:    Number(form.stock_usado)     || 0,
      alerta_minimo:  Number(form.alerta_minimo)   || 30,
      costo_unitario: Number(form.costo_unitario)  || 0,
      notas:          form.notas          || null,
      updated_at:     new Date().toISOString(),
    };

    if (form.id) {
      const { data, error: err } = await supabase
        .from('inventory').update(payload).eq('id', form.id).select().single();
      if (err) throw new Error(err.message);
      setItems(prev => prev.map(i => i.id === form.id ? data : i));
      return data;
    } else {
      const { data, error: err } = await supabase
        .from('inventory').insert(payload).select().single();
      if (err) throw new Error(err.message);
      setItems(prev => [...prev, data]);
      return data;
    }
  }, [userId]);

  // ── Eliminar ──────────────────────────────────────────────────
  const deleteItem = useCallback(async (id) => {
    const { error: err } = await supabase.from('inventory').delete().eq('id', id);
    if (err) throw new Error(err.message);
    setItems(prev => prev.filter(i => i.id !== id));
  }, []);

  // ── Registrar SALIDA (tomar pieza / usar material) ────────────
  // Incrementa stock_usado. El disponible baja automáticamente.
  const updateUsed = useCallback(async (id, cantidad) => {
    const item = items.find(i => i.id === id);
    if (!item) return;
    const disponible = item.stock_inicial + item.entradas - item.stock_usado;
    const newUsado   = item.stock_usado + Math.min(cantidad, disponible);
    const { data, error: err } = await supabase
      .from('inventory')
      .update({ stock_usado: newUsado, updated_at: new Date().toISOString() })
      .eq('id', id).select().single();
    if (err) throw new Error(err.message);
    setItems(prev => prev.map(i => i.id === id ? data : i));
    return data;
  }, [items]);

  // ── Registrar ENTRADA (reposición / compra de material) ───────
  // Incrementa entradas. El disponible sube automáticamente.
  const addEntrada = useCallback(async (id, cantidad) => {
    const item = items.find(i => i.id === id);
    if (!item) return;
    const newEntradas = item.entradas + Number(cantidad);
    const { data, error: err } = await supabase
      .from('inventory')
      .update({ entradas: newEntradas, updated_at: new Date().toISOString() })
      .eq('id', id).select().single();
    if (err) throw new Error(err.message);
    setItems(prev => prev.map(i => i.id === id ? data : i));
    return data;
  }, [items]);

  // ── Derived ───────────────────────────────────────────────────
  const stockBajoItems = items.filter(i =>
    (i.stock_inicial + i.entradas - i.stock_usado) <= i.alerta_minimo
  );

  const valorTotal = items.reduce((sum, i) => {
    const disp = i.stock_inicial + i.entradas - i.stock_usado;
    return sum + (Math.max(0, disp) * (i.costo_unitario || 0));
  }, 0);

  return {
    items, loading, error,
    saveItem, deleteItem,
    updateUsed,   // registrar salida
    addEntrada,   // registrar entrada / reposición
    stockBajoItems,
    valorTotal,
    reload: load,
  };
}
