import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';

/*
═══════════════════════════════════════════════════════════════
  SQL — ejecuta en Supabase → SQL Editor

  -- Tabla de pedidos
  create table if not exists orders (
    id               bigint generated by default as identity primary key,
    user_id          uuid references auth.users not null default auth.uid(),
    cliente_nombre   text not null,
    cliente_telefono text,
    cliente_email    text,
    patron_nombre    text not null,
    patron_emoji     text default '🧶',
    materiales       jsonb default '[]',  -- [{inv_id, nombre, cantidad, costo_unit}]
    horas            numeric not null default 0,
    costo_hora       numeric not null default 40,
    overhead_pct     numeric not null default 10,  -- 10%
    margen_pct       numeric not null default 30,  -- 30%
    precio_venta     numeric,            -- calculado o manual
    precio_manual    boolean default false,
    estado           text not null default 'pendiente',  -- pendiente|en_proceso|listo|entregado|cancelado
    fecha_pedido     date not null default now(),
    fecha_entrega    date,
    notas            text,
    anticipo         numeric default 0,
    created_at       timestamptz default now(),
    updated_at       timestamptz default now()
  );

  alter table orders enable row level security;
  create policy "Ver mis pedidos"    on orders for select using (auth.uid() = user_id);
  create policy "Crear mis pedidos"  on orders for insert with check (auth.uid() = user_id);
  create policy "Editar mis pedidos" on orders for update using (auth.uid() = user_id);
  create policy "Borrar mis pedidos" on orders for delete using (auth.uid() = user_id);
═══════════════════════════════════════════════════════════════
*/

// Fórmula: (Materiales + Horas×costoHora) × (1 + overhead/100) × (1 + margen/100)
export function calcPrecio({ materiales = [], horas = 0, costo_hora = 40, overhead_pct = 10, margen_pct = 30 }) {
  const costoMat   = materiales.reduce((s, m) => s + (m.cantidad * m.costo_unit), 0);
  const costoMO    = horas * costo_hora;
  const subtotal   = costoMat + costoMO;
  const conOverhead = subtotal * (1 + overhead_pct / 100);
  const conMargen   = conOverhead * (1 + margen_pct / 100);
  return {
    costoMat:     parseFloat(costoMat.toFixed(2)),
    costoMO:      parseFloat(costoMO.toFixed(2)),
    subtotal:     parseFloat(subtotal.toFixed(2)),
    conOverhead:  parseFloat(conOverhead.toFixed(2)),
    precioFinal:  parseFloat(conMargen.toFixed(2)),
  };
}

export function useOrders(userId) {
  const [orders,  setOrders]  = useState([]);
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState(null);

  const load = useCallback(async () => {
    if (!userId) return;
    setLoading(true);
    setError(null);
    const { data, error: err } = await supabase
      .from('orders')
      .select('*')
      .eq('user_id', userId)
      .order('fecha_entrega', { ascending: true, nullsFirst: false });
    if (err) setError(err.message);
    else     setOrders(data || []);
    setLoading(false);
  }, [userId]);

  useEffect(() => { load(); }, [load]);

  const saveOrder = useCallback(async (form) => {
    const payload = {
      user_id:          userId,
      cliente_nombre:   form.cliente_nombre,
      cliente_telefono: form.cliente_telefono  || null,
      cliente_email:    form.cliente_email     || null,
      patron_nombre:    form.patron_nombre,
      patron_emoji:     form.patron_emoji      || '🧶',
      materiales:       form.materiales        || [],
      horas:            Number(form.horas)     || 0,
      costo_hora:       Number(form.costo_hora)|| 40,
      overhead_pct:     Number(form.overhead_pct) || 10,
      margen_pct:       Number(form.margen_pct)   || 30,
      precio_venta:     Number(form.precio_venta) || 0,
      precio_manual:    form.precio_manual     || false,
      estado:           form.estado            || 'pendiente',
      fecha_pedido:     form.fecha_pedido      || new Date().toISOString().slice(0, 10),
      fecha_entrega:    form.fecha_entrega     || null,
      notas:            form.notas             || null,
      anticipo:         Number(form.anticipo)  || 0,
      updated_at:       new Date().toISOString(),
    };

    if (form.id) {
      const { data, error: err } = await supabase
        .from('orders').update(payload).eq('id', form.id).select().single();
      if (err) throw new Error(err.message);
      setOrders(prev => prev.map(o => o.id === form.id ? data : o));
      return data;
    } else {
      const { data, error: err } = await supabase
        .from('orders').insert(payload).select().single();
      if (err) throw new Error(err.message);
      setOrders(prev => [data, ...prev]);
      return data;
    }
  }, [userId]);

  const deleteOrder = useCallback(async (id) => {
    const { error: err } = await supabase.from('orders').delete().eq('id', id);
    if (err) throw new Error(err.message);
    setOrders(prev => prev.filter(o => o.id !== id));
  }, []);

  const updateEstado = useCallback(async (id, estado) => {
    const { data, error: err } = await supabase
      .from('orders').update({ estado, updated_at: new Date().toISOString() })
      .eq('id', id).select().single();
    if (err) throw new Error(err.message);
    setOrders(prev => prev.map(o => o.id === id ? data : o));
    return data;
  }, []);

  // Pedidos que vencen en ≤ 2 días
  const proximosVencer = orders.filter(o => {
    if (!o.fecha_entrega || o.estado === 'entregado' || o.estado === 'cancelado') return false;
    const dias = Math.ceil((new Date(o.fecha_entrega) - new Date()) / 86400000);
    return dias <= 2 && dias >= 0;
  });

  const stats = {
    total:      orders.length,
    pendientes: orders.filter(o => o.estado === 'pendiente').length,
    enProceso:  orders.filter(o => o.estado === 'en_proceso').length,
    listos:     orders.filter(o => o.estado === 'listo').length,
    entregados: orders.filter(o => o.estado === 'entregado').length,
    ingresos:   orders
      .filter(o => o.estado === 'entregado')
      .reduce((s, o) => s + (o.precio_venta || 0), 0),
    porCobrar:  orders
      .filter(o => !['entregado','cancelado'].includes(o.estado))
      .reduce((s, o) => s + ((o.precio_venta || 0) - (o.anticipo || 0)), 0),
  };

  return {
    orders, loading, error,
    saveOrder, deleteOrder, updateEstado,
    proximosVencer, stats,
    reload: load,
  };
}
