import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';
import {
  getPendingSales, addPendingSale, removePendingSale,
  getPendingStock, addPendingStock, removePendingStock,
  getTotalPending,
} from '../lib/offlineQueue';

/*
═══════════════════════════════════════════════════════════════
  SQL — ejecuta en Supabase → SQL Editor
═══════════════════════════════════════════════════════════════

-- 1. Productos del stock de tienda
create table if not exists store_products (
  id             bigint generated by default as identity primary key,
  user_id        uuid references auth.users not null default auth.uid(),
  nombre         text not null,
  emoji          text not null default '🧸',
  categoria      text not null default 'amigurumi',  -- amigurumi | flor | llavero | otro
  descripcion    text,
  precio_venta   numeric not null default 0,
  stock_inicial  numeric not null default 0,
  stock_vendido  numeric not null default 0,
  patron_id      bigint references patterns(id) on delete set null,
  patron_nombre  text,   -- copia denormalizada por si se borra el patrón
  activo         boolean not null default true,
  color_hex      text default '#FAD2E1',
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);

alter table store_products enable row level security;
create policy "Ver mis productos"    on store_products for select using (auth.uid() = user_id);
create policy "Crear mis productos"  on store_products for insert with check (auth.uid() = user_id);
create policy "Editar mis productos" on store_products for update using (auth.uid() = user_id);
create policy "Borrar mis productos" on store_products for delete using (auth.uid() = user_id);

-- 2. Eventos / lugares de venta
create table if not exists store_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users not null default auth.uid(),
  nombre      text not null,
  tipo        text not null default 'bazar',  -- bazar | tienda | papeleria | mercado | online | otro
  fecha_inicio date,
  fecha_fin    date,
  notas        text,
  activo       boolean not null default true,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

alter table store_events enable row level security;
create policy "Ver mis eventos"    on store_events for select using (auth.uid() = user_id);
create policy "Crear mis eventos"  on store_events for insert with check (auth.uid() = user_id);
create policy "Editar mis eventos" on store_events for update using (auth.uid() = user_id);
create policy "Borrar mis eventos" on store_events for delete using (auth.uid() = user_id);

-- 3. Ventas individuales
create table if not exists store_sales (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users not null default auth.uid(),
  product_id  bigint references store_products(id) on delete set null,
  event_id    bigint references store_events(id) on delete set null,
  product_nombre  text not null,   -- copia por si se borra el producto
  product_emoji   text default '🧸',
  event_nombre    text,            -- copia por si se borra el evento
  cantidad    numeric not null default 1,
  precio_unit numeric not null default 0,
  total       numeric not null default 0,
  fecha       date not null default now(),
  notas       text,
  created_at  timestamptz default now()
);

alter table store_sales enable row level security;
create policy "Ver mis ventas"    on store_sales for select using (auth.uid() = user_id);
create policy "Crear mis ventas"  on store_sales for insert with check (auth.uid() = user_id);
create policy "Editar mis ventas" on store_sales for update using (auth.uid() = user_id);
create policy "Borrar mis ventas" on store_sales for delete using (auth.uid() = user_id);

═══════════════════════════════════════════════════════════════
*/

export const CATEGORIAS = [
  { id: 'amigurumi', label: 'Amigurumi',  emoji: '🧸' },
  { id: 'flor',      label: 'Flor',       emoji: '🌸' },
  { id: 'llavero',   label: 'Llavero',    emoji: '🔑' },
  { id: 'otro',      label: 'Otro',       emoji: '🎀' },
];

export const TIPOS_EVENTO = [
  { id: 'bazar',      label: 'Bazar',      emoji: '🏪' },
  { id: 'tienda',     label: 'Tienda',     emoji: '🏬' },
  { id: 'papeleria',  label: 'Papelería',  emoji: '📚' },
  { id: 'mercado',    label: 'Mercado',    emoji: '🛒' },
  { id: 'online',     label: 'En línea',   emoji: '💻' },
  { id: 'otro',       label: 'Otro',       emoji: '📍' },
];

// ─────────────────────────────────────────────────────────────
// useStore
// ─────────────────────────────────────────────────────────────
export function useStore(userId) {
  const [products, setProducts] = useState([]);
  const [events,   setEvents]   = useState([]);
  const [sales,    setSales]    = useState([]);
  const [loading,  setLoading]  = useState(true);
  const [error,    setError]    = useState(null);

  // ── Conectividad ──────────────────────────────────────────
  const [isOnline, setIsOnline] = useState(navigator.onLine);
  const [pendingCount, setPendingCount] = useState(getTotalPending);

  // ── Carga inicial ─────────────────────────────────────────
  const load = useCallback(async () => {
    if (!userId) return;
    setLoading(true);
    setError(null);

    const [rProd, rEvt, rSales] = await Promise.all([
      supabase.from('store_products').select('*').eq('user_id', userId).order('nombre'),
      supabase.from('store_events').select('*').eq('user_id', userId).order('created_at', { ascending: false }),
      supabase.from('store_sales').select('*').eq('user_id', userId).order('created_at', { ascending: false }),
    ]);

    if (rProd.error)  setError(rProd.error.message);
    if (rEvt.error)   setError(rEvt.error.message);
    if (rSales.error) setError(rSales.error.message);

    setProducts(rProd.data  || []);
    setEvents(rEvt.data     || []);
    setSales(rSales.data    || []);
    setLoading(false);
  }, [userId]);

  useEffect(() => { load(); }, [load]);

  // ── PRODUCTOS ─────────────────────────────────────────────
  const saveProduct = useCallback(async (form) => {
    const payload = {
      user_id:       userId,
      nombre:        form.nombre,
      emoji:         form.emoji         || '🧸',
      categoria:     form.categoria     || 'amigurumi',
      descripcion:   form.descripcion   || null,
      precio_venta:  Number(form.precio_venta) || 0,
      stock_inicial: Number(form.stock_inicial) || 0,
      stock_vendido: Number(form.stock_vendido) || 0,
      patron_id:     form.patron_id     || null,
      patron_nombre: form.patron_nombre || null,
      activo:        form.activo !== false,
      color_hex:     form.color_hex     || '#FAD2E1',
      updated_at:    new Date().toISOString(),
    };

    if (form.id) {
      const { data, error: err } = await supabase
        .from('store_products').update(payload).eq('id', form.id).select().single();
      if (err) throw new Error(err.message);
      setProducts(prev => prev.map(p => p.id === form.id ? data : p));
      return data;
    } else {
      const { data, error: err } = await supabase
        .from('store_products').insert(payload).select().single();
      if (err) throw new Error(err.message);
      setProducts(prev => [...prev, data].sort((a, b) => a.nombre.localeCompare(b.nombre)));
      return data;
    }
  }, [userId]);

  const deleteProduct = useCallback(async (id) => {
    const { error: err } = await supabase.from('store_products').delete().eq('id', id);
    if (err) throw new Error(err.message);
    setProducts(prev => prev.filter(p => p.id !== id));
  }, []);

  // ── EVENTOS ───────────────────────────────────────────────
  const saveEvent = useCallback(async (form) => {
    const payload = {
      user_id:     userId,
      nombre:      form.nombre,
      tipo:        form.tipo        || 'bazar',
      fecha_inicio: form.fecha_inicio || null,
      fecha_fin:   form.fecha_fin   || null,
      notas:       form.notas       || null,
      activo:      form.activo !== false,
      updated_at:  new Date().toISOString(),
    };

    if (form.id) {
      const { data, error: err } = await supabase
        .from('store_events').update(payload).eq('id', form.id).select().single();
      if (err) throw new Error(err.message);
      setEvents(prev => prev.map(e => e.id === form.id ? data : e));
      return data;
    } else {
      const { data, error: err } = await supabase
        .from('store_events').insert(payload).select().single();
      if (err) throw new Error(err.message);
      setEvents(prev => [data, ...prev]);
      return data;
    }
  }, [userId]);

  const deleteEvent = useCallback(async (id) => {
    const { error: err } = await supabase.from('store_events').delete().eq('id', id);
    if (err) throw new Error(err.message);
    setEvents(prev => prev.filter(e => e.id !== id));
  }, []);

  // ── VENTAS ────────────────────────────────────────────────
  const registerSale = useCallback(async ({ product, event, cantidad, precio_unit, fecha, notas }) => {
    const cant  = Number(cantidad)    || 1;
    const price = Number(precio_unit) || product.precio_venta || 0;
    const total = cant * price;

    const salePayload = {
      user_id:        userId,
      product_id:     product.id,
      event_id:       event?.id    || null,
      product_nombre: product.nombre,
      product_emoji:  product.emoji,
      event_nombre:   event?.nombre || null,
      cantidad:       cant,
      precio_unit:    price,
      total,
      fecha:          fecha || new Date().toISOString().slice(0, 10),
      notas:          notas || null,
    };

    if (!navigator.onLine) {
      // Optimistic update local
      const tempSale = { ...salePayload, id: 'offline_' + Date.now() };
      const newVendido = (product.stock_vendido || 0) + cant;
      setSales(prev => [tempSale, ...prev]);
      setProducts(prev => prev.map(p =>
        p.id === product.id ? { ...p, stock_vendido: newVendido } : p
      ));
      addPendingSale(salePayload);
      setPendingCount(getTotalPending());
      return tempSale;
    }

    // 1. Insertar venta
    const { data: saleData, error: saleErr } = await supabase
      .from('store_sales').insert(salePayload).select().single();
    if (saleErr) throw new Error(saleErr.message);

    // 2. Actualizar stock_vendido del producto
    const newVendido = (product.stock_vendido || 0) + cant;
    const { data: prodData, error: prodErr } = await supabase
      .from('store_products')
      .update({ stock_vendido: newVendido, updated_at: new Date().toISOString() })
      .eq('id', product.id).select().single();
    if (prodErr) throw new Error(prodErr.message);

    setSales(prev => [saleData, ...prev]);
    setProducts(prev => prev.map(p => p.id === product.id ? prodData : p));
    return saleData;
  }, [userId]);

  const deleteSale = useCallback(async (sale) => {
    // Borra la venta y devuelve stock al producto
    const { error: err } = await supabase.from('store_sales').delete().eq('id', sale.id);
    if (err) throw new Error(err.message);

    // Revertir stock_vendido
    const product = products.find(p => p.id === sale.product_id);
    if (product) {
      const newVendido = Math.max(0, (product.stock_vendido || 0) - sale.cantidad);
      const { data: prodData } = await supabase
        .from('store_products')
        .update({ stock_vendido: newVendido, updated_at: new Date().toISOString() })
        .eq('id', product.id).select().single();
      if (prodData) setProducts(prev => prev.map(p => p.id === product.id ? prodData : p));
    }

    setSales(prev => prev.filter(s => s.id !== sale.id));
  }, [products]);

  // ── Agregar stock (reposición) ─────────────────────────────
  const addStock = useCallback(async (productId, cantidad) => {
    const product = products.find(p => p.id === productId);
    if (!product) return;

    if (!navigator.onLine) {
      // Optimistic update local
      const newStock = (product.stock_inicial || 0) + Number(cantidad);
      setProducts(prev => prev.map(p =>
        p.id === productId ? { ...p, stock_inicial: newStock } : p
      ));
      addPendingStock({ productId, cantidad: Number(cantidad) });
      setPendingCount(getTotalPending());
      return { ...product, stock_inicial: newStock };
    }

    const newStock = (product.stock_inicial || 0) + Number(cantidad);
    const { data, error: err } = await supabase
      .from('store_products')
      .update({ stock_inicial: newStock, updated_at: new Date().toISOString() })
      .eq('id', productId).select().single();
    if (err) throw new Error(err.message);
    setProducts(prev => prev.map(p => p.id === productId ? data : p));
    return data;
  }, [products]);

  // ── Sincronización de operaciones pendientes ──────────────
  const _syncPending = useCallback(async () => {
    if (!navigator.onLine || !userId) return;

    const pendingSales = getPendingSales();
    const pendingStock = getPendingStock();
    if (pendingSales.length === 0 && pendingStock.length === 0) return;

    let synced = 0;

    // ── Sincronizar ventas ────────────────────────────────────
    for (const sale of pendingSales) {
      try {
        const { _id, _savedAt, ...saleData } = sale;

        // 1. Insertar venta en store_sales
        const { error: saleErr } = await supabase
          .from('store_sales').insert(saleData).select().single();
        if (saleErr) throw saleErr;

        // 2. Leer stock_vendido ACTUAL de Supabase (no del estado local)
        const { data: freshProduct, error: fetchErr } = await supabase
          .from('store_products')
          .select('stock_vendido')
          .eq('id', sale.product_id)
          .single();
        if (fetchErr) throw fetchErr;

        // 3. Sumar solo la cantidad de esta venta al valor real de DB
        const newVendido = (freshProduct.stock_vendido || 0) + sale.cantidad;
        const { error: updateErr } = await supabase
          .from('store_products')
          .update({ stock_vendido: newVendido, updated_at: new Date().toISOString() })
          .eq('id', sale.product_id);
        if (updateErr) throw updateErr;

        removePendingSale(_id);
        synced++;
      } catch (e) {
        console.error('Error sincronizando venta:', e);
      }
    }

    // Sincronizar stock
    for (const entry of pendingStock) {
      try {
        const product = products.find(p => p.id === entry.productId);
        if (!product) { removePendingStock(entry._id); continue; }
        const newStock = (product.stock_inicial || 0) + entry.cantidad;
        const { error } = await supabase.from('store_products')
          .update({ stock_inicial: newStock, updated_at: new Date().toISOString() })
          .eq('id', entry.productId);
        if (error) throw error;
        removePendingStock(entry._id);
        synced++;
      } catch (e) {
        console.error('Error sincronizando stock:', e);
      }
    }

    setPendingCount(getTotalPending());

    // Recargar datos frescos de Supabase
    if (synced > 0) await load();

    return synced;
  }, [userId, products, load]);

  // ── Conectividad (detección + sync automático) ────────────
  useEffect(() => {
    const handleOnline  = () => { setIsOnline(true); _syncPending(); };
    const handleOffline = () => setIsOnline(false);
    window.addEventListener('online',  handleOnline);
    window.addEventListener('offline', handleOffline);
    // Sync al montar si hay red y hay pendientes
    if (navigator.onLine) _syncPending();
    return () => {
      window.removeEventListener('online',  handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, [_syncPending]);

  // ── Derived / stats ───────────────────────────────────────
  const statsGlobal = {
    totalProductos:  products.length,
    totalPiezas:     products.reduce((s, p) => s + (p.stock_inicial || 0), 0),
    totalVendidas:   products.reduce((s, p) => s + (p.stock_vendido || 0), 0),
    totalIngresos:   sales.reduce((s, v) => s + (v.total || 0), 0),
    sinStock:        products.filter(p => (p.stock_inicial - p.stock_vendido) <= 0).length,
  };

  // Resumen por evento
  const eventStats = (eventId) => {
    const ventasEvento = sales.filter(s => s.event_id === eventId);
    return {
      piezas:   ventasEvento.reduce((s, v) => s + v.cantidad, 0),
      ingresos: ventasEvento.reduce((s, v) => s + v.total, 0),
      ventas:   ventasEvento,
    };
  };


  // ── Costing: guarda desglose y crea/actualiza producto ───
  const saveCostingAndProduct = useCallback(async (form) => {
    // 1. Crear el producto en store_products con el precio final
    const productPayload = {
      user_id:       userId,
      nombre:        form.nombre,
      emoji:         '🧸',
      categoria:     'amigurumi',
      precio_venta:  form.precio_final,
      stock_inicial: 0,
      stock_vendido: 0,
      patron_id:     form.patron_id    || null,
      patron_nombre: form.patron_nombre || null,
      activo:        true,
      color_hex:     '#FAD2E1',
      updated_at:    new Date().toISOString(),
    };
    const { data: prodData, error: prodErr } = await supabase
      .from('store_products').insert(productPayload).select().single();
    if (prodErr) throw new Error(prodErr.message);
    setProducts(prev => [...prev, prodData].sort((a, b) => a.nombre.localeCompare(b.nombre)));

    // 2. Guardar el costing vinculado al producto
    const costingPayload = {
      user_id:         userId,
      product_id:      prodData.id,
      patron_id:       form.patron_id    || null,
      nombre:          form.nombre,
      materiales:      form.materiales   || [],
      horas:           form.horas        || 0,
      costo_hora:      form.costo_hora   || 40,
      overhead_pct:    form.overhead_pct || 10,
      margen_pct:      form.margen_pct   || 30,
      precio_sugerido: form.precio_sugerido,
      precio_final:    form.precio_final,
      notas:           form.notas        || null,
      updated_at:      new Date().toISOString(),
    };
    const { error: costErr } = await supabase
      .from('store_costings').insert(costingPayload);
    if (costErr) throw new Error(costErr.message);

    return prodData;
  }, [userId]);

  return {
    products, events, sales,
    loading, error, isOnline, pendingCount,
    saveProduct, deleteProduct,
    saveEvent,   deleteEvent,
    registerSale, deleteSale,
    addStock,
    saveCostingAndProduct,
    statsGlobal, eventStats,
    reload: load,
    syncPending: _syncPending,
  };
}

// ─────────────────────────────────────────────────────────────
// useStoreCostings  —  desglose de costos vinculado a patrón
// ─────────────────────────────────────────────────────────────
/*
SQL — ejecuta en Supabase → SQL Editor

create table if not exists store_costings (
  id              bigint generated by default as identity primary key,
  user_id         uuid references auth.users not null default auth.uid(),
  product_id      bigint references store_products(id) on delete set null,
  patron_id       bigint references patterns(id) on delete set null,
  patron_nombre   text,
  nombre          text not null,
  materiales      jsonb default '[]',
  horas           numeric not null default 0,
  costo_hora      numeric not null default 40,
  costo_total     numeric not null default 0,
  precio_sugerido numeric not null default 0,
  precio_final    numeric not null default 0,
  precio_manual   boolean not null default false,
  notas           text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

alter table store_costings enable row level security;
create policy "Ver mis costings"    on store_costings for select using (auth.uid() = user_id);
create policy "Crear mis costings"  on store_costings for insert with check (auth.uid() = user_id);
create policy "Editar mis costings" on store_costings for update using (auth.uid() = user_id);
create policy "Borrar mis costings" on store_costings for delete using (auth.uid() = user_id);
*/

export function useStoreCostings(userId) {
  const [costings, setCostings] = useState([]);
  const [loading,  setLoading]  = useState(true);

  const load = useCallback(async () => {
    if (!userId) return;
    setLoading(true);
    const { data } = await supabase
      .from('store_costings').select('*').eq('user_id', userId)
      .order('created_at', { ascending: false });
    setCostings(data || []);
    setLoading(false);
  }, [userId]);

  useEffect(() => { load(); }, [load]);

  const saveCosting = useCallback(async (form, saveProduct) => {
    const payload = {
      user_id:         userId,
      patron_id:       form.patron_id       || null,
      patron_nombre:   form.patron_nombre   || null,
      nombre:          form.nombre,
      materiales:      form.materiales      || [],
      horas:           Number(form.horas)   || 0,
      costo_hora:      Number(form.costo_hora) || 40,
      overhead_pct:    Number(form.overhead_pct)    || 10,
      margen_pct:      Number(form.margen_pct)      || 30,
      costo_total:     Number(form.costo_total)     || 0,
      precio_sugerido: Number(form.precio_sugerido) || 0,
      precio_final:    Number(form.precio_final)    || 0,
      precio_manual:   form.precio_manual   || false,
      notas:           form.notas           || null,
      updated_at:      new Date().toISOString(),
    };

    let costing;
    if (form.id) {
      const { data, error } = await supabase
        .from('store_costings').update(payload).eq('id', form.id).select().single();
      if (error) throw new Error(error.message);
      costing = data;
      setCostings(prev => prev.map(c => c.id === form.id ? data : c));
    } else {
      const { data, error } = await supabase
        .from('store_costings').insert(payload).select().single();
      if (error) throw new Error(error.message);
      costing = data;
      setCostings(prev => [data, ...prev]);
    }

    // Crear/actualizar producto en Tienda si saveProduct está disponible
    if (saveProduct) {
      const productPayload = {
        id:           form.product_id || undefined,
        nombre:       form.nombre,
        emoji:        form.emoji         || '🧸',
        categoria:    form.categoria     || 'amigurumi',
        precio_venta: Number(form.precio_final) || 0,
        stock_inicial: Number(form.stock_inicial) || 0,
        stock_vendido: 0,
        patron_id:    form.patron_id     || null,
        patron_nombre: form.patron_nombre || null,
        color_hex:    form.color_hex     || '#FAD2E1',
      };
      const prod = await saveProduct(productPayload);
      // Vincular product_id al costing
      if (prod?.id && prod.id !== form.product_id) {
        await supabase.from('store_costings')
          .update({ product_id: prod.id }).eq('id', costing.id);
        setCostings(prev => prev.map(c => c.id === costing.id ? { ...c, product_id: prod.id } : c));
      }
      return { costing, product: prod };
    }

    return { costing };
  }, [userId]);

  const deleteCosting = useCallback(async (id) => {
    const { error } = await supabase.from('store_costings').delete().eq('id', id);
    if (error) throw new Error(error.message);
    setCostings(prev => prev.filter(c => c.id !== id));
  }, []);

  return { costings, loading, saveCosting, deleteCosting, reload: load };
}
