import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';

/*
═══════════════════════════════════════════════════════════════
  SQL — ejecuta en Supabase → SQL Editor
═══════════════════════════════════════════════════════════════

-- 1. Productos del stock de tienda
create table if not exists store_products (
  id             bigint generated by default as identity primary key,
  user_id        uuid references auth.users not null default auth.uid(),
  nombre         text not null,
  emoji          text not null default '🧸',
  categoria      text not null default 'amigurumi',  -- amigurumi | flor | llavero | otro
  descripcion    text,
  precio_venta   numeric not null default 0,
  stock_inicial  numeric not null default 0,
  stock_vendido  numeric not null default 0,
  patron_id      bigint references patterns(id) on delete set null,
  patron_nombre  text,   -- copia denormalizada por si se borra el patrón
  activo         boolean not null default true,
  color_hex      text default '#FAD2E1',
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);

alter table store_products enable row level security;
create policy "Ver mis productos"    on store_products for select using (auth.uid() = user_id);
create policy "Crear mis productos"  on store_products for insert with check (auth.uid() = user_id);
create policy "Editar mis productos" on store_products for update using (auth.uid() = user_id);
create policy "Borrar mis productos" on store_products for delete using (auth.uid() = user_id);

-- 2. Eventos / lugares de venta
create table if not exists store_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users not null default auth.uid(),
  nombre      text not null,
  tipo        text not null default 'bazar',  -- bazar | tienda | papeleria | mercado | online | otro
  fecha_inicio date,
  fecha_fin    date,
  notas        text,
  activo       boolean not null default true,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

alter table store_events enable row level security;
create policy "Ver mis eventos"    on store_events for select using (auth.uid() = user_id);
create policy "Crear mis eventos"  on store_events for insert with check (auth.uid() = user_id);
create policy "Editar mis eventos" on store_events for update using (auth.uid() = user_id);
create policy "Borrar mis eventos" on store_events for delete using (auth.uid() = user_id);

-- 3. Ventas individuales
create table if not exists store_sales (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users not null default auth.uid(),
  product_id  bigint references store_products(id) on delete set null,
  event_id    bigint references store_events(id) on delete set null,
  product_nombre  text not null,   -- copia por si se borra el producto
  product_emoji   text default '🧸',
  event_nombre    text,            -- copia por si se borra el evento
  cantidad    numeric not null default 1,
  precio_unit numeric not null default 0,
  total       numeric not null default 0,
  fecha       date not null default now(),
  notas       text,
  created_at  timestamptz default now()
);

alter table store_sales enable row level security;
create policy "Ver mis ventas"    on store_sales for select using (auth.uid() = user_id);
create policy "Crear mis ventas"  on store_sales for insert with check (auth.uid() = user_id);
create policy "Editar mis ventas" on store_sales for update using (auth.uid() = user_id);
create policy "Borrar mis ventas" on store_sales for delete using (auth.uid() = user_id);

═══════════════════════════════════════════════════════════════
*/

export const CATEGORIAS = [
  { id: 'amigurumi', label: 'Amigurumi',  emoji: '🧸' },
  { id: 'flor',      label: 'Flor',       emoji: '🌸' },
  { id: 'llavero',   label: 'Llavero',    emoji: '🔑' },
  { id: 'otro',      label: 'Otro',       emoji: '🎀' },
];

export const TIPOS_EVENTO = [
  { id: 'bazar',      label: 'Bazar',      emoji: '🏪' },
  { id: 'tienda',     label: 'Tienda',     emoji: '🏬' },
  { id: 'papeleria',  label: 'Papelería',  emoji: '📚' },
  { id: 'mercado',    label: 'Mercado',    emoji: '🛒' },
  { id: 'online',     label: 'En línea',   emoji: '💻' },
  { id: 'otro',       label: 'Otro',       emoji: '📍' },
];

// ─────────────────────────────────────────────────────────────
// useStore
// ─────────────────────────────────────────────────────────────
export function useStore(userId) {
  const [products, setProducts] = useState([]);
  const [events,   setEvents]   = useState([]);
  const [sales,    setSales]    = useState([]);
  const [loading,  setLoading]  = useState(true);
  const [error,    setError]    = useState(null);

  // ── Carga inicial ─────────────────────────────────────────
  const load = useCallback(async () => {
    if (!userId) return;
    setLoading(true);
    setError(null);

    const [rProd, rEvt, rSales] = await Promise.all([
      supabase.from('store_products').select('*').eq('user_id', userId).order('nombre'),
      supabase.from('store_events').select('*').eq('user_id', userId).order('created_at', { ascending: false }),
      supabase.from('store_sales').select('*').eq('user_id', userId).order('created_at', { ascending: false }),
    ]);

    if (rProd.error)  setError(rProd.error.message);
    if (rEvt.error)   setError(rEvt.error.message);
    if (rSales.error) setError(rSales.error.message);

    setProducts(rProd.data  || []);
    setEvents(rEvt.data     || []);
    setSales(rSales.data    || []);
    setLoading(false);
  }, [userId]);

  useEffect(() => { load(); }, [load]);

  // ── PRODUCTOS ─────────────────────────────────────────────
  const saveProduct = useCallback(async (form) => {
    const payload = {
      user_id:       userId,
      nombre:        form.nombre,
      emoji:         form.emoji         || '🧸',
      categoria:     form.categoria     || 'amigurumi',
      descripcion:   form.descripcion   || null,
      precio_venta:  Number(form.precio_venta) || 0,
      stock_inicial: Number(form.stock_inicial) || 0,
      stock_vendido: Number(form.stock_vendido) || 0,
      patron_id:     form.patron_id     || null,
      patron_nombre: form.patron_nombre || null,
      activo:        form.activo !== false,
      color_hex:     form.color_hex     || '#FAD2E1',
      updated_at:    new Date().toISOString(),
    };

    if (form.id) {
      const { data, error: err } = await supabase
        .from('store_products').update(payload).eq('id', form.id).select().single();
      if (err) throw new Error(err.message);
      setProducts(prev => prev.map(p => p.id === form.id ? data : p));
      return data;
    } else {
      const { data, error: err } = await supabase
        .from('store_products').insert(payload).select().single();
      if (err) throw new Error(err.message);
      setProducts(prev => [...prev, data].sort((a, b) => a.nombre.localeCompare(b.nombre)));
      return data;
    }
  }, [userId]);

  const deleteProduct = useCallback(async (id) => {
    const { error: err } = await supabase.from('store_products').delete().eq('id', id);
    if (err) throw new Error(err.message);
    setProducts(prev => prev.filter(p => p.id !== id));
  }, []);

  // ── EVENTOS ───────────────────────────────────────────────
  const saveEvent = useCallback(async (form) => {
    const payload = {
      user_id:     userId,
      nombre:      form.nombre,
      tipo:        form.tipo        || 'bazar',
      fecha_inicio: form.fecha_inicio || null,
      fecha_fin:   form.fecha_fin   || null,
      notas:       form.notas       || null,
      activo:      form.activo !== false,
      updated_at:  new Date().toISOString(),
    };

    if (form.id) {
      const { data, error: err } = await supabase
        .from('store_events').update(payload).eq('id', form.id).select().single();
      if (err) throw new Error(err.message);
      setEvents(prev => prev.map(e => e.id === form.id ? data : e));
      return data;
    } else {
      const { data, error: err } = await supabase
        .from('store_events').insert(payload).select().single();
      if (err) throw new Error(err.message);
      setEvents(prev => [data, ...prev]);
      return data;
    }
  }, [userId]);

  const deleteEvent = useCallback(async (id) => {
    const { error: err } = await supabase.from('store_events').delete().eq('id', id);
    if (err) throw new Error(err.message);
    setEvents(prev => prev.filter(e => e.id !== id));
  }, []);

  // ── VENTAS ────────────────────────────────────────────────
  const registerSale = useCallback(async ({ product, event, cantidad, precio_unit, fecha, notas }) => {
    const cant  = Number(cantidad)   || 1;
    const price = Number(precio_unit) || product.precio_venta || 0;
    const total = cant * price;

    // 1. Insertar venta
    const salePayload = {
      user_id:        userId,
      product_id:     product.id,
      event_id:       event?.id    || null,
      product_nombre: product.nombre,
      product_emoji:  product.emoji,
      event_nombre:   event?.nombre || null,
      cantidad:       cant,
      precio_unit:    price,
      total,
      fecha:          fecha || new Date().toISOString().slice(0, 10),
      notas:          notas || null,
    };

    const { data: saleData, error: saleErr } = await supabase
      .from('store_sales').insert(salePayload).select().single();
    if (saleErr) throw new Error(saleErr.message);

    // 2. Actualizar stock_vendido del producto
    const newVendido = (product.stock_vendido || 0) + cant;
    const { data: prodData, error: prodErr } = await supabase
      .from('store_products')
      .update({ stock_vendido: newVendido, updated_at: new Date().toISOString() })
      .eq('id', product.id).select().single();
    if (prodErr) throw new Error(prodErr.message);

    setSales(prev => [saleData, ...prev]);
    setProducts(prev => prev.map(p => p.id === product.id ? prodData : p));
    return saleData;
  }, [userId]);

  const deleteSale = useCallback(async (sale) => {
    // Borra la venta y devuelve stock al producto
    const { error: err } = await supabase.from('store_sales').delete().eq('id', sale.id);
    if (err) throw new Error(err.message);

    // Revertir stock_vendido
    const product = products.find(p => p.id === sale.product_id);
    if (product) {
      const newVendido = Math.max(0, (product.stock_vendido || 0) - sale.cantidad);
      const { data: prodData } = await supabase
        .from('store_products')
        .update({ stock_vendido: newVendido, updated_at: new Date().toISOString() })
        .eq('id', product.id).select().single();
      if (prodData) setProducts(prev => prev.map(p => p.id === product.id ? prodData : p));
    }

    setSales(prev => prev.filter(s => s.id !== sale.id));
  }, [products]);

  // ── Agregar stock (reposición) ─────────────────────────────
  const addStock = useCallback(async (productId, cantidad) => {
    const product = products.find(p => p.id === productId);
    if (!product) return;
    const newStock = (product.stock_inicial || 0) + Number(cantidad);
    const { data, error: err } = await supabase
      .from('store_products')
      .update({ stock_inicial: newStock, updated_at: new Date().toISOString() })
      .eq('id', productId).select().single();
    if (err) throw new Error(err.message);
    setProducts(prev => prev.map(p => p.id === productId ? data : p));
    return data;
  }, [products]);

  // ── Derived / stats ───────────────────────────────────────
  const statsGlobal = {
    totalProductos:  products.length,
    totalPiezas:     products.reduce((s, p) => s + (p.stock_inicial || 0), 0),
    totalVendidas:   products.reduce((s, p) => s + (p.stock_vendido || 0), 0),
    totalIngresos:   sales.reduce((s, v) => s + (v.total || 0), 0),
    sinStock:        products.filter(p => (p.stock_inicial - p.stock_vendido) <= 0).length,
  };

  // Resumen por evento
  const eventStats = (eventId) => {
    const ventasEvento = sales.filter(s => s.event_id === eventId);
    return {
      piezas:   ventasEvento.reduce((s, v) => s + v.cantidad, 0),
      ingresos: ventasEvento.reduce((s, v) => s + v.total, 0),
      ventas:   ventasEvento,
    };
  };

  return {
    products, events, sales,
    loading, error,
    saveProduct, deleteProduct,
    saveEvent,   deleteEvent,
    registerSale, deleteSale,
    addStock,
    statsGlobal, eventStats,
    reload: load,
  };
}
