-- ═══════════════════════════════════════════════════════════════
--  SCRIPT COMPLETO DE BASE DE DATOS — AmiPattern
--  Ejecutar en Supabase → SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════
--  1. TABLAS EXISTENTES (ya deberían existir, se saltan si existen)
-- ═══════════════════════════════════════════════════════════════

-- patterns
create table if not exists patterns (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users not null default auth.uid(),
  nombre      text not null,
  emoji       text not null default '🧶',
  dificultad  text not null default 'Principiante',
  estado      text not null default 'En progreso',
  talla       text,
  aguja       text,
  hilos       text[] default '{}',
  materiales  text,
  notas       text,
  pasos       jsonb default '[]',
  imagen_url  text,
  color       text not null default '#FAD2E1',
  fecha       date not null default now(),
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

alter table patterns enable row level security;
do $$ begin create policy "Ver mis patrones" on patterns for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear mis patrones" on patterns for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar mis patrones" on patterns for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar mis patrones" on patterns for delete using (auth.uid() = user_id); exception when others then null; end; $$;
create index if not exists patterns_user_id_idx on patterns(user_id);

-- inventory
create table if not exists inventory (
  id              bigint generated by default as identity primary key,
  user_id         uuid references auth.users not null default auth.uid(),
  tipo            text not null default 'hilo',
  nombre          text not null,
  marca           text,
  color           text,
  color_hex       text,
  subtipo         text,
  grosor_mm       numeric,
  tipo_gancho     text,
  unidad          text default 'pz',
  stock_inicial   numeric not null default 0,
  entradas        numeric not null default 0,
  stock_usado     numeric not null default 0,
  alerta_minimo   numeric default 0,
  costo_unitario  numeric default 0,
  notas           text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

alter table inventory enable row level security;
do $$ begin create policy "Ver mi inventario" on inventory for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear mi inventario" on inventory for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar mi inventario" on inventory for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar mi inventario" on inventory for delete using (auth.uid() = user_id); exception when others then null; end; $$;
create index if not exists inventory_user_id_idx on inventory(user_id);

-- orders
create table if not exists orders (
  id                    bigint generated by default as identity primary key,
  user_id               uuid references auth.users not null default auth.uid(),
  cliente_nombre        text not null,
  cliente_telefono      text,
  cliente_email         text,
  patron_nombre         text not null,
  patron_emoji          text default '🧶',
  materiales            jsonb default '[]',
  horas                 numeric not null default 0,
  costo_hora            numeric not null default 40,
  overhead_pct          numeric not null default 10,
  margen_pct            numeric not null default 30,
  precio_venta          numeric,
  precio_manual         boolean default false,
  estado                text not null default 'pendiente',
  inventario_descontado boolean not null default false,
  fecha_pedido          date not null default now(),
  fecha_entrega         date,
  anticipo              numeric default 0,
  notas                 text,
  created_at            timestamptz default now(),
  updated_at            timestamptz default now()
);

alter table orders enable row level security;
do $$ begin create policy "Ver mis pedidos" on orders for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear mis pedidos" on orders for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar mis pedidos" on orders for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar mis pedidos" on orders for delete using (auth.uid() = user_id); exception when others then null; end; $$;
create index if not exists orders_user_id_idx on orders(user_id);

-- store_products
create table if not exists store_products (
  id             bigint generated by default as identity primary key,
  user_id        uuid references auth.users not null default auth.uid(),
  nombre         text not null,
  emoji          text not null default '🧸',
  categoria      text not null default 'amigurumi',
  descripcion    text,
  precio_venta   numeric not null default 0,
  stock_inicial  numeric not null default 0,
  stock_vendido  numeric not null default 0,
  patron_id      bigint references patterns(id) on delete set null,
  patron_nombre  text,
  activo         boolean not null default true,
  color_hex      text default '#FAD2E1',
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);

alter table store_products enable row level security;
do $$ begin create policy "Ver mis productos" on store_products for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear mis productos" on store_products for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar mis productos" on store_products for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar mis productos" on store_products for delete using (auth.uid() = user_id); exception when others then null; end; $$;

-- store_events
create table if not exists store_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users not null default auth.uid(),
  nombre      text not null,
  tipo        text not null default 'bazar',
  fecha_inicio date,
  fecha_fin    date,
  notas        text,
  activo       boolean not null default true,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

alter table store_events enable row level security;
do $$ begin create policy "Ver mis eventos" on store_events for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear mis eventos" on store_events for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar mis eventos" on store_events for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar mis eventos" on store_events for delete using (auth.uid() = user_id); exception when others then null; end; $$;

-- store_sales
create table if not exists store_sales (
  id             bigint generated by default as identity primary key,
  user_id        uuid references auth.users not null default auth.uid(),
  product_id     bigint references store_products(id) on delete set null,
  event_id       bigint references store_events(id) on delete set null,
  product_nombre text not null,
  product_emoji  text default '🧸',
  event_nombre   text,
  cantidad       numeric not null default 1,
  precio_unit    numeric not null default 0,
  total          numeric not null default 0,
  fecha          date not null default now(),
  notas          text,
  created_at     timestamptz default now()
);

alter table store_sales enable row level security;
do $$ begin create policy "Ver mis ventas" on store_sales for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear mis ventas" on store_sales for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar mis ventas" on store_sales for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar mis ventas" on store_sales for delete using (auth.uid() = user_id); exception when others then null; end; $$;

-- store_costings
create table if not exists store_costings (
  id              bigint generated by default as identity primary key,
  user_id         uuid references auth.users not null default auth.uid(),
  product_id      bigint references store_products(id) on delete set null,
  patron_id       bigint references patterns(id) on delete set null,
  patron_nombre   text,
  nombre          text not null,
  materiales      jsonb default '[]',
  horas           numeric not null default 0,
  costo_hora      numeric not null default 40,
  overhead_pct    numeric not null default 10,
  margen_pct      numeric not null default 30,
  costo_total     numeric not null default 0,
  precio_sugerido numeric not null default 0,
  precio_final    numeric not null default 0,
  precio_manual   boolean not null default false,
  notas           text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

alter table store_costings enable row level security;
do $$ begin create policy "Ver mis costings" on store_costings for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear mis costings" on store_costings for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar mis costings" on store_costings for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar mis costings" on store_costings for delete using (auth.uid() = user_id); exception when others then null; end; $$;

-- ═══════════════════════════════════════════════════════════════
--  2. NUEVAS TABLAS — Módulo Lista de Precios (Boutique)
-- ═══════════════════════════════════════════════════════════════

-- price_config (1 fila por usuario)
create table if not exists price_config (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users not null default auth.uid(),
  pago_por_hora   numeric not null default 60,
  margen_boutique numeric not null default 0.35,
  margen_propio   numeric not null default 0.20,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),
  constraint unique_user_price_config unique (user_id)
);

alter table price_config enable row level security;
do $$ begin create policy "Ver config" on price_config for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear config" on price_config for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar config" on price_config for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar config" on price_config for delete using (auth.uid() = user_id); exception when others then null; end; $$;

-- price_list
create table if not exists price_list (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users not null default auth.uid(),
  nombre          text not null,
  emoji           text default '🧸',
  size            text,
  costo_material  numeric not null default 0,
  horas           numeric not null default 0,
  costo_empaque   numeric not null default 0,
  nota            text,
  patron_id       bigint references patterns(id) on delete set null,
  orden           integer default 0,
  activo          boolean default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

alter table price_list enable row level security;
do $$ begin create policy "Ver items" on price_list for select using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Crear items" on price_list for insert with check (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Editar items" on price_list for update using (auth.uid() = user_id); exception when others then null; end; $$;
do $$ begin create policy "Borrar items" on price_list for delete using (auth.uid() = user_id); exception when others then null; end; $$;

create index if not exists price_list_user_id_idx on price_list(user_id);
create index if not exists price_list_orden_idx on price_list(user_id, orden);
